[package]
name = "xenon"
version = "0.1.0"
authors = ["Steve Pryde <steve@stevepryde.com>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
#warp = "0.2.2"
tokio = { version = "0.2.20", features = ["macros", "rt-threaded", "sync"] }
log = "0.4.8"
thiserror = "1.0.16"
uuid = { version = "0.8.1", features = ["v4"] }
futures = "0.3.5"
pretty_env_logger = "0.4.0"
hyper = "0.13.5"
