[package]
name = "xenon"
version = "0.1.0"
authors = ["Steve Pryde <steve@stevepryde.com>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
tokio = { version = "0.2.20", features = ["macros", "rt-threaded", "sync"] }
log = "0.4.8"
thiserror = "1.0.16"
uuid = { version = "0.8.1", features = ["v4"] }
pretty_env_logger = "0.4.0"
hyper = "0.13.5"
serde_json = { version = "1.0", features = ["preserve_order"] }
serde = { version = "1.0", features = ["derive"] }
bytes = "0.5.4"
serde_yaml = "0.8.11"
chrono = "0.4.11"
indexmap = "1.3.2"
