[package]
name = "xenon"
version = "0.3.1"
authors = ["Steve Pryde <steve@stevepryde.com>"]
edition = "2018"
license = "MIT"
description = "Xenon is a WebDriver proxy, for running multiple WebDriver sessions through a single hub"
homepage = "https://github.com/stevepryde/xenon"
repository = "https://github.com/stevepryde/xenon"
readme = "README.md"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
tokio = { version = "0.2.20", features = ["macros", "rt-threaded", "sync", "time", "process"] }
log = "0.4.8"
thiserror = "1.0.16"
uuid = { version = "0.8.1", features = ["v4"] }
hyper = "0.13.5"
serde_json = { version = "1.0", features = ["preserve_order"] }
serde = { version = "1.0", features = ["derive"] }
bytes = "0.5.4"
serde_yaml = "0.8.11"
chrono = "0.4.11"
indexmap = "1.3.2"
env_logger = "0.7.1"
structopt = "0.3.14"
